# Generated by Django 2.1 on 2019-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('like', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User_table',
            },
        ),
    ]
